name: Build Core

env:
  HUSKY: 0

permissions:
  contents: write

on:
  push:
    tags:
      - v*.*.*
      - v*.*.*-debug.*

jobs:
  # New job to filter if 'core' folder was changed
  filter_core:
    runs-on: ubuntu-latest
    outputs:
      core_changed: ${{ steps.filter.outputs.core }}
    steps:
      - uses: actions/checkout@v4
      - name: Filter core changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            core:
              - 'core/**'

  build_core:
    needs: [filter_core]
    if: ${{ needs.filter_core.outputs.core_changed == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: windows-latest
            target: x86_64-pc-windows-msvc

    name: stable - ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    defaults:
      run:
        working-directory: ./core

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}

      - name: Detect build type
        id: build-type
        shell: bash
        run: |
          if [[ "${GITHUB_REF##*/}" == *"-debug."* ]]; then
            echo "BUILD_TYPE=debug" >> "$GITHUB_OUTPUT"
          else
            echo "BUILD_TYPE=release" >> "$GITHUB_OUTPUT"
          fi

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./core/target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}-${{ hashFiles('core/Cargo.lock') }}-${{ steps.build-type.outputs.BUILD_TYPE }}
          restore-keys: |
            ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}-

      - name: Log Cargo and target folder sizes
        shell: bash
        run: |
          echo "Cargo registry index:"
          du -sh ~/.cargo/registry/index/ || true
          echo "Cargo registry cache:"
          du -sh ~/.cargo/registry/cache/ || true
          echo "Cargo git db:"
          du -sh ~/.cargo/git/db/ || true
          echo "core/target:"
          du -sh ./core/target/ || true

      - name: Build
        shell: bash
        run: |
          BUILD_TYPE="${{ steps.build-type.outputs.BUILD_TYPE }}"
          if [ "$BUILD_TYPE" = "release" ]; then
            cargo build --release --target ${{ matrix.settings.target }}
          else
            cargo build --target ${{ matrix.settings.target }}
          fi

      - name: Log Cargo and target folder sizes after build
        shell: bash
        run: |
          echo "Cargo registry index:"
          du -sh ~/.cargo/registry/index/ || true
          echo "Cargo registry cache:"
          du -sh ~/.cargo/registry/cache/ || true
          echo "Cargo git db:"
          du -sh ~/.cargo/git/db/ || true
          echo "core/target:"
          du -sh ./core/target/ || true

      - name: Rename and move binary
        shell: bash
        run: |
          mkdir -p dist
          cp target/${{ matrix.settings.target }}/${{ steps.build-type.outputs.BUILD_TYPE }}/core${{ matrix.settings.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }} dist/lumea-${{ matrix.settings.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lumea-${{ matrix.settings.target }}
          path: ./core/dist/lumea-${{ matrix.settings.target }}
          if-no-files-found: error

  build_api:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          cd api
          npm ci

      - name: Build api
        shell: bash
        run: |
          cd api
          npm run build

      - name: Log dist
        run: |
          cd api
          find dist

      - name: Copy dist
        shell: bash
        run: |
          mkdir package/dist
          cp -r api/dist/* package/dist
          find package/dist

      - name: Build package
        shell: bash
        run: |
          cd package
          npm ci --ignore-scripts
          npm install esbuild
          npm run release:prebuild
          npm run build

      - name: List dist
        run: |
          find package/dist

      - name: Publish package
        shell: bash
        run: |
          cd package
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release_core:
    needs: build_core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List files
        run: |
          find dist
          find dist -type f

      - name: Generate changelog since last release
        id: changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ || echo "")
          echo "Last tag: $LAST_TAG"
          if [ -n "$LAST_TAG" ]; then
            git log --pretty=format:'* %s (%h)' $LAST_TAG..HEAD > body.md
          else
            echo "Initial release" > body.md
          fi

      - name: Check if prerelease
        id: prerelease
        run: |
          TAG="${GITHUB_REF##*/}"
          if [[ "$TAG" == *"-debug."* ]]; then
            echo "PRERELEASE=true" >> "$GITHUB_OUTPUT"
          else
            echo "PRERELEASE=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: body.md
          prerelease: ${{ contains(github.ref_name, '-debug.') }}
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
