name: Build Core

on:
  - workflow_dispatch
  - push:
      tags:
        - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build_core:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: windows-latest
            build: cargo build --release --target x86_64-pc-windows-msvc
            target: x86_64-pc-windows-msvc
    name: stable - ${{ matrix.settings.target }} - node@20
    runs-on: ${{ matrix.settings.host }}
    defaults:
      run:
        working-directory: ./core
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        if: ${{ !matrix.settings.docker }}
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./core/target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}

      - name: Build with Cargo
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: core-${{ matrix.settings.target }}
          path: ./core/target/${{ matrix.settings.target }}/release/core${{ matrix.settings.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}
          if-no-files-found: error

  release:
    needs: build_core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Generate changelog since last release
        id: changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ || echo "")
          echo "Last tag: $LAST_TAG"
          if [ -n "$LAST_TAG" ]; then
            git log --pretty=format:'* %s (%h)' $LAST_TAG..HEAD > body.md
          else
            echo "Initial release" > body.md
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: body.md
          files: |
            dist/core-*/core*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
